[package]
name = "eventd"
version = "0.3.2"
authors = ["zrkn <zrkn@email.su>"]
edition = "2018"
description = "Simple observer-like event dispatcher"
repository = "https://github.com/zrkn/eventd/"
keywords = ["event", "delegate", "observer"]
license = "MIT"

[dependencies]
slab = "0.4"
